apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend
  labels:
    app: product-backend
    tier: backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: product-backend
      tier: backend
  template:
    metadata:
      labels:
        app: product-backend
        tier: backend
    spec:
           
      initContainers:
      - name: wait-for-mysql
        image: mariadb:10.11.3
        command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL to be ready..."
              until mysql -h "$DB_HOST" -u "$DB_HEALTHCHECK_USER" -e "SELECT 1" >/dev/null 2>&1; do
                sleep 3
              done
              echo "MySQL is ready"
        env:
        - name: DB_HOST  
          valueFrom:
            configMapKeyRef:
              name: product-backend-env-vars  
              key: DB_HOST

        - name: DB_HEALTHCHECK_USER  
          valueFrom:
            secretKeyRef:
              name: mysql-secret  
              key: DB_HEALTHCHECK_USER
              
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_HEALTHCHECK_PASSWORD
            
      containers:
      - name: product-backend-cont
        image: "{{ .Values.image.imageName }}:{{ .Values.image.imageVersion }}"   # vaheeddockerhub/product-img
        imagePullPolicy: IfNotPresent
        ports:
        - name: product
          containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: product-backend-env-vars

        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 20
        
        readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
         
        livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: product-backend        # Service name
  labels:
    app: product-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: product-backend
    tier: backend
  ports:
  - name: product
    protocol: "TCP"
    port: 8080
    targetPort: 8080
    #nodePort: 32123
